# Глобальные настройки
global:
  namespace: dz7
  ingress:
    enabled: true
    host: arch.homework
    className: ""
  jwt:
    signingKey: shared_microservices_secret_key
    tokenIssuer: microservices-auth
    tokenAudiences: microservices
  postgresql:
    auth:
      username: postgres
      password: postgres
    service:
      port: 5432
  rabbitmq:
    auth:
      username: guest
      password: guest
    service:
      port: 5672

# Настройки сервисов
order:
  enabled: true
  replicaCount: 2
  image:
    repository: lamoed/otusdz7_order-service
    tag: 1.0.0
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080
  database:
    name: orders
  rabbitmq:
    vhost: /
  env:
    BILLING_SERVICE_URL: http://billing-service:8081
    NOTIFICATION_SERVICE_URL: http://notification-service:8082

billing:
  enabled: true
  replicaCount: 2
  image:
    repository: lamoed/otusdz7_billing-service
    tag: 1.0.0
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8081
  database:
    name: billing
  rabbitmq:
    vhost: /

notification:
  enabled: true
  replicaCount: 2
  image:
    repository: lamoed/otusdz7_notification-service
    tag: 1.0.0
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8082
  database:
    name: notifications
  rabbitmq:
    vhost: /
  smtp:
    host: mailhog
    port: 1025
    fromEmail: notification@example.com

# Настройки инфраструктуры
postgres:
  enabled: true
  image:
    repository: bitnami/postgresql
    tag: 17.2.0
    pullPolicy: IfNotPresent
  persistence:
    enabled: false
    size: 1Gi
  service:
    port: 5432
  databases:
    - orders
    - billing
    - notifications

rabbitmq:
  enabled: true
  image:
    repository: rabbitmq
    tag: 3.12-management
    pullPolicy: IfNotPresent
  persistence:
    enabled: false
    size: 1Gi
  service:
    port: 5672
    managementPort: 15672

mailhog:
  enabled: true
  image:
    repository: mailhog/mailhog
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 1025
    uiPort: 8025 