{{ if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
  namespace: {{ $.Values.global.namespace }}
  labels:
    app: postgres
data:
  init-databases.sh: |-
    #!/bin/bash
    set -e

    # Создаем необходимые базы данных
    {{- range .Values.databases }}
    PGPASSWORD=${POSTGRES_PASSWORD} psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" --dbname "${POSTGRES_DB}" <<-EOSQL
        CREATE DATABASE {{ . }};
        GRANT ALL PRIVILEGES ON DATABASE {{ . }} TO ${POSTGRES_USER};
    EOSQL
    {{- end }}
{{ end }} 